# Generated by Django 5.0.6 on 2024-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Manager'), (3, 'DeliveryCrew'), (4, 'Customer')], default=5, null=True),
        ),
    ]
