# Generated by Django 5.0.6 on 2024-05-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='category_id',
        ),
    ]
