# Generated by Django 5.0.6 on 2024-05-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_item_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default=0.0, max_length=256),
            preserve_default=False,
        ),
    ]
