# Generated by Django 5.0.6 on 2024-05-17 20:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('item_uid', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category_name', models.CharField(max_length=255)),
                ('category_uid', models.UUIDField()),
                ('assigned_crew_id', models.UUIDField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
