# Generated by Django 5.0.6 on 2024-05-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='assigned_crew_id',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='category_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
