# Generated by Django 5.0.6 on 2024-05-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_user_cart_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='item_id',
            new_name='item',
        ),
    ]
