# Generated by Django 5.0.6 on 2024-05-17 20:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_assigned_crew_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='assigned_crew_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='category_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
