# Generated by Django 5.0.6 on 2024-05-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_customer_id_cart_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='item_id',
        ),
    ]
