# Generated by Django 5.0.6 on 2024-05-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_assigned_crew_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='category_uid',
            field=models.UUIDField(),
        ),
    ]
