# Generated by Django 5.0.6 on 2024-05-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_category_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='assigned_crew_id',
            field=models.UUIDField(),
        ),
    ]
