# Generated by Django 5.0.6 on 2024-06-06 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_customer_id_cart_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='menu.item'),
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='item_id',
        ),
    ]
